version: '3.8'

services:
  db:
    image: "postgres:17"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: projectx
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "projectx", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      start_period: 10s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=projectx
      - DB_USER=postgres
      - DB_PASSWORD=xxx
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    deploy:
      replicas: 3
    networks:
      - app-network

  nginx:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

